env:
  global:
    secure: C3UQt4RiLQWzugbiTzw00lg8+/lCUPK3FjSxck4BnU7+uB3wdh7qaZp88mG/hUrrB5tASW316UowzRCYTItPtsNuEOLK3x+KxKZBW5fpyvaSOZrSlPV7qv1kJjGQirskgZxH1aH/g/fHknBXsifawPT6it63INk/SVE/szfEHfg=
before_install:
- npm install -g npm
- npm install bower -global
- npm install tsd -global
- rm ci -r -free
- mkdir ci
- cd ci
- git init
- git config user.name "autodeploy-travis"
- git config user.email "travis"
- git remote add github https://github.com/jThreeJS/jThree
- git pull github gh-pages
- git checkout gh-pages
- ls
- cd ..
install:
- npm install
- tsd install
- bower install
script:
- glup travis
after_script:
- if $TRAVIS_BRANCH -ne "gh-pages"; then
- cd ci
- git checkout gh-pages
- git add -A
- git commit -m "document update by travis"
- git push --force https://$GHTOKEN@github.com/jThreeJS/jThree gh-pages:gh-pages
- cd ..
- else
- echo "gh-pages publish was skipped."
- fi
language: node_js
node_js:
- 0.12
notifications:
  slack:
    secure: JQPxyKx9YYx0AgG2ZwFJdd3P/wEQ3HLksKgBF7IWUVwFkHifhJNRG608EiJf6JK/pJoebMt9gSJGEcTIrko3f5qlrNBdRXKvqUR57G0He84wL1QyZl4AZ5PPeesf352dr2zYKvX/TeWM5EDYuzjv4io5mgRR914hBON4GdpCOA4=
