env:
  global: 
    secure: C3UQt4RiLQWzugbiTzw00lg8+/lCUPK3FjSxck4BnU7+uB3wdh7qaZp88mG/hUrrB5tASW316UowzRCYTItPtsNuEOLK3x+KxKZBW5fpyvaSOZrSlPV7qv1kJjGQirskgZxH1aH/g/fHknBXsifawPT6it63INk/SVE/szfEHfg=
before_install:
- npm install -g npm
- rm ci -r
- mkdir ci
- cd ci
- git init
- git config user.name "autodeploy-travis"
- git config user.email "travis"
- git remote add github https://github.com/jThreeJS/jThree
- git pull github gh-pages
- git branch gh-pages
- ls
- cd ..
install:
- npm install grunt-cli -save-dev
- npm install grunt-contrib-qunit -save-dev
- npm install
script:
- grunt travis --verbose --force --branch=$TRAVIS_BRANCH
after_script:
- if $TRAVIS_BRANCH -ne "gh-pages"; then
- cd ci
- git add -A
- git commit -m "document update by travis"
- git push --force https://$GHTOKEN@github.com/jThreeJS/jThree gh-pages
- cd ..
- else
- echo "gh-pages publish was skipped."
- fi
language: node_js
node_js:
- 0.12
